FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npx prisma generate

ENV SKIP_BUILD_DB_CALLS=true
RUN npm run build
ENV SKIP_BUILD_DB_CALLS=

EXPOSE 3002



CMD ["npm", "run", "start"]

