name: CI/CD scrolladex-frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "scrolladex-fe/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push scrolladex-frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scrolladex-fe
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scrolladex-frontend:latest

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/scrolladex-frontend:latest
            docker stop scrolladex-frontend
            docker rm scrolladex-frontend
            docker run -d --name scrolladex-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/scrolladex-frontend:latest
