name: CI/CD scrolladex-backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "scrolladex-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push scrolladex-backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scrolladex-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scrolladex-backend:latest
